#!/usr/bin/env python
"""Regenerate the workbench data files from measured results.

The workbench displays numbers.  Every one of them must come from a
validation run or from the implementation itself, never from a literal
typed into a component.  This script is the only thing that writes
src/data/*.json, and it reads only from:

  honjo-py/hjm/masamune/capability.py     the declared capability sets
  validation/results/exp_masamune.json    the Masamune measurements
  validation/results/exp_honjo.json       the conformance suite
  ../dmitri/publications/graphical-chemistry-generator/results/
      exp_generator.json                  the Meibutsu measurements

Run from the honjo-masamune directory:

    python src/data/generate.py

If a result file is missing, this fails loudly rather than emitting a
partial file: a workbench showing half-real numbers is worse than one
that will not build.
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "honjo-py"))

RESULTS = os.path.join(ROOT, "validation", "results")
GENERATOR_RESULTS = os.path.abspath(
    os.path.join(
        ROOT, "..", "dmitri", "publications",
        "graphical-chemistry-generator", "results",
    )
)


def load(path: str) -> dict:
    if not os.path.exists(path):
        raise SystemExit(
            f"missing required result file: {path}\n"
            "run the validation experiments before regenerating."
        )
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def finite(obj):
    """Replace NaN/Infinity with null.

    Python's json module emits bare NaN and Infinity, which are not
    valid JSON and which every JavaScript bundler rejects.  A NaN here
    is meaningful -- it marks a statistic that was undefined rather than
    zero -- so it becomes null and the consuming component treats it as
    absent.
    """
    if isinstance(obj, dict):
        return {k: finite(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [finite(v) for v in obj]
    if isinstance(obj, float):
        if obj != obj or obj in (float("inf"), float("-inf")):
            return None
    return obj


def write(name: str, obj: dict) -> None:
    dest = os.path.join(HERE, name)
    text = json.dumps(finite(obj), indent=1, allow_nan=False)
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"  {name}  {os.path.getsize(dest):,} bytes")


def build_masamune() -> dict:
    from hjm.masamune.capability import CAPABILITY, FEATURES

    res = load(os.path.join(RESULTS, "exp_masamune.json"))["results"]
    m1 = res["M1_supplied_fraction"]
    m2 = res["M2_capability_containment"]
    m3 = res["M3_verdict_coverage"]
    m4 = res["M4_format_disagreement"]

    return {
        "_provenance": (
            "generated by src/data/generate.py from "
            "honjo-py/hjm/masamune/capability.py and "
            "validation/results/exp_masamune.json — do not edit by hand"
        ),
        "features": sorted(FEATURES),
        "capability": {k: sorted(v) for k, v in CAPABILITY.items()},
        "supplied": {
            "n_structures": m1["n_structures"],
            "mean": m1["smiles_mean_phi"],
            "median": m1["smiles_median_phi"],
            "min": m1["smiles_min_phi"],
            "max": m1["smiles_max_phi"],
            "stdev": m1["smiles_stdev_phi"],
            "rows": [
                {
                    "molecule": r["molecule"],
                    "phi": r["smiles_phi"],
                    "phi_with_medium": r["smiles_phi_with_medium"],
                    "n_atoms": r["n_atoms"],
                    "n_heavy": r["n_heavy"],
                }
                for r in m1["rows"]
                if "smiles_phi" in r
            ],
        },
        "containment": {
            "n_pairs": m2["n_pairs"],
            "n_consistent": m2["n_consistent"],
            "n_refused_statically": m2["n_refused_statically"],
            "rows": m2["rows"],
        },
        "verdicts": {
            "labels_realised": m3["labels_realised"],
            "n_labels_defined": m3["n_labels_defined"],
            "value_bearing_failures": m3["value_bearing_failures"],
            "rows": m3["rows"],
        },
        "disagreement": {
            "n_pairs": m4["n_pairs"],
            "n_undetected": m4["n_undetected_by_identity"],
            "rows": m4["rows"],
        },
    }


def build_honjo() -> dict:
    H = load(os.path.join(RESULTS, "exp_honjo.json"))["results"]

    def item(code, name, measured, programs):
        return {"item": code, "name": name,
                "measured": measured, "programs": programs}

    return {
        "_provenance": (
            "generated by src/data/generate.py from "
            "validation/results/exp_honjo.json — do not edit by hand"
        ),
        "conformance": [
            item("C1", "no sharp cut",
                 f"{H['H1_no_sharp_cut']['n_values_below_floor']} sub-floor values",
                 H["H1_no_sharp_cut"]["n_programs"]),
            item("C2", "provenance monotone",
                 f"{H['H2_provenance_monotone']['n_violations']} violations",
                 H["H2_provenance_monotone"]["n_programs"]),
            item("C3", "verdicts realised",
                 f"{H['H3_verdict_realisation']['value_bearing_failures']} "
                 "value-bearing failures",
                 H["H3_verdict_realisation"]["n_programs"]),
            item("C4", "conflation control",
                 f"{H['H4_conflation_control']['n_distinct_outcomes']} distinct, "
                 f"{H['H4_conflation_control']['n_wrapped_outcomes']} wrapped",
                 H["H4_conflation_control"]["n_programs"]),
            item("C5", "cell counts distinguish", "closed vs unclosed", 2),
            item("C6", "delocalisation not a count",
                 f"{H['H6_deloc_not_a_count']['n_readable_per_pair']} "
                 "readable per-pair", 1),
            item("C7", "resolution gate",
                 f"{H['H7_resolution_gate']['n_refused']}/"
                 f"{H['H7_resolution_gate']['n_sub_resolution']} refused",
                 H["H7_resolution_gate"]["n_programs"]),
            item("C8", "scope recorded",
                 f"{H['H8_target_equivalence_scope']['n_in_scope']} in scope, "
                 f"{H['H8_target_equivalence_scope']['n_excluded']} excluded",
                 H["H8_target_equivalence_scope"]["n_total"]),
        ],
        "floor_sweep": H["H1_no_sharp_cut"]["rows"],
        "deloc_sweep": H["H6_deloc_sweep"]["rows"],
        "resolution_gate": H["H7_resolution_gate"]["rows"],
        "examples": H["H3_verdict_realisation"]["rows"],
    }


def build_meibutsu() -> dict:
    G = load(os.path.join(GENERATOR_RESULTS, "exp_generator.json"))["results"]
    return {
        "_provenance": (
            "generated by src/data/generate.py from "
            "graphical-chemistry-generator/results/exp_generator.json "
            "— do not edit by hand"
        ),
        "self_visibility": {
            "n": G["G2_self_visibility"]["n_structures"],
            "n_exactly_one": G["G2_self_visibility"]["n_exactly_one"],
            "max_deviation": G["G2_self_visibility"]["max_deviation_from_one"],
        },
        "decay": {k: v for k, v in G["G3_decay"].items() if k != "note"},
        "inversion": {
            "n": G["G4_inversion"]["n"],
            "ranked_first": G["G4_inversion"]["n_ranked_first"],
            "address_unique": G["G4_inversion"]["n_address_unique"],
            "rows": G["G4_inversion"]["rows"],
        },
        "bulk_identity": {
            k: v for k, v in G["G5_bulk_identity"].items() if k != "note"
        },
        "capacity": G["G6_bulk_capacity"]["rows"],
        "floor": G["G7_resolution_floor"]["rows"],
        "control": G["G8_phaseless_control"]["rows"],
        "display": G["G9_display_identity"]["rows"],
    }


def build_spectra() -> dict:
    """Reference spectra for the interference panel.

    Taken from the same NIST-derived database the validation used, so
    the panel cannot drift from the measurements: transcribing these by
    hand produced three wrong entries on the first attempt.
    """
    db = os.path.abspath(
        os.path.join(ROOT, "..", "dmitri", "categorical-compound-database")
    )
    sys.path.insert(0, db)
    from categorical_compound_database import COMPOUNDS

    pick = ["H2", "N2", "O2", "HF", "HCl", "CO", "H2O", "CO2", "SO2",
            "H2S", "NH3", "CH4", "C2H2", "C2H4", "C6H6", "CH3OH",
            "CCl4", "HCN"]
    return {
        "_provenance": (
            "generated by src/data/generate.py from the NIST CCCBDB "
            "frequencies in categorical-compound-database "
            "— do not edit by hand"
        ),
        "omega_ref": 4401.0,
        "spectra": {
            k: {
                "modes": COMPOUNDS[k]["modes"],
                "formula": COMPOUNDS[k]["formula"],
                "b_rot": COMPOUNDS[k].get("B_rot"),
                "type": COMPOUNDS[k]["type"],
            }
            for k in pick
            if k in COMPOUNDS
        },
    }


def build_records() -> dict:
    """Record sets the workbench offers plans as a virtual file system.

    The browser has no disk, so `source lib : smiles at "compounds.smi"`
    resolves against these rather than a path.  Drawn from the same
    corpus the validation used.
    """
    sys.path.insert(0, os.path.join(ROOT, "validation", "src"))
    from corpus import DRUGLIKE, SYMMETRIC

    def recs(pairs):
        return [{"name": n, "text": s} for n, s in pairs]

    return {
        "_provenance": (
            "generated by src/data/generate.py from "
            "validation/src/corpus.py -- do not edit by hand"
        ),
        "files": {
            "compounds.smi": recs(DRUGLIKE),
            "symmetric.smi": recs([(n, s) for n, s, _ in SYMMETRIC]),
            "one.smi": [{"name": "ethanol", "text": "CCO"}],
            "mixed.smi": recs(DRUGLIKE[:6]) + [
                {"name": "ethanol-explicit", "text": "[CH3][CH2][OH]"},
                {"name": "ammonia-explicit", "text": "[NH3]"},
                {"name": "malformed", "text": "C((("},
            ],
        },
    }


def main() -> None:
    print("regenerating workbench data from measured results")
    write("masamune.json", build_masamune())
    write("honjo.json", build_honjo())
    write("meibutsu.json", build_meibutsu())
    write("spectra.json", build_spectra())
    write("records.json", build_records())
    print("done — every displayed number now traces to a result file")


if __name__ == "__main__":
    main()
