/**
 * /validation — Bounded Phase Space Validation Dashboard
 * =====================================================
 * One axiom → 142 predictions across 7 domains, 24 orders of magnitude.
 * All results loaded from static JSON generated by validate_bounded_phase_space.py.
 */
import { useEffect, useMemo, useState } from "react";
import Head from "next/head";
import Link from "next/link";

const BATTERIES = [
  { key: "nuclear_structure", label: "Nuclear structure", color: "#f97316" },
  { key: "partition_extinction", label: "Partition extinction", color: "#3b82f6" },
  { key: "electromagnetism", label: "Electromagnetism", color: "#a855f7" },
  { key: "transport", label: "Transport", color: "#22c55e" },
  { key: "atomic", label: "Atomic structure", color: "#ef4444" },
  { key: "chromatography", label: "Chromatography", color: "#58E6D9" },
  { key: "propagation_lag", label: "Propagation lag (c)", color: "#fbbf24" },
  { key: "universal_eos", label: "Universal EOS", color: "#ec4899" },
  { key: "dark_ratio", label: "Dark sector ratio", color: "#6366f1" },
  { key: "tetration", label: "Categorical enumeration", color: "#14b8a6" },
];

// Extract every (predicted, measured, error_pct) record from a battery JSON
function extractErrors(json) {
  const errors = [];
  const walk = (node) => {
    if (node === null || node === undefined) return;
    if (Array.isArray(node)) {
      node.forEach(walk);
      return;
    }
    if (typeof node === "object") {
      if (typeof node.error_pct === "number") {
        errors.push(node.error_pct);
      }
      Object.values(node).forEach(walk);
    }
  };
  walk(json);
  return errors;
}

export default function Validation() {
  const [summary, setSummary] = useState(null);
  const [batteries, setBatteries] = useState({});
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const load = async () => {
      try {
        const summaryRes = await fetch("/validation/summary.json").then((r) => r.json());
        setSummary(summaryRes);
        const entries = await Promise.all(
          BATTERIES.map(async (b) => {
            try {
              const json = await fetch(`/validation/${b.key}.json`).then((r) => r.json());
              return [b.key, json];
            } catch {
              return [b.key, null];
            }
          })
        );
        setBatteries(Object.fromEntries(entries));
      } finally {
        setLoaded(true);
      }
    };
    load();
  }, []);

  // Aggregate all error percentages across batteries
  const allErrors = useMemo(() => {
    const all = [];
    for (const b of BATTERIES) {
      const json = batteries[b.key];
      if (json) all.push(...extractErrors(json).map((e) => ({ e, battery: b.key, color: b.color })));
    }
    return all;
  }, [batteries]);

  // Histogram bins for |error| on log scale
  const histogram = useMemo(() => {
    if (allErrors.length === 0) return [];
    const bins = [
      { label: "< 1%", min: 0, max: 1, count: 0 },
      { label: "1–5%", min: 1, max: 5, count: 0 },
      { label: "5–15%", min: 5, max: 15, count: 0 },
      { label: "15–50%", min: 15, max: 50, count: 0 },
      { label: "50–100%", min: 50, max: 100, count: 0 },
      { label: "> 100%", min: 100, max: Infinity, count: 0 },
    ];
    for (const { e } of allErrors) {
      const abs = Math.abs(e);
      for (const bin of bins) {
        if (abs >= bin.min && abs < bin.max) {
          bin.count += 1;
          break;
        }
      }
    }
    return bins;
  }, [allErrors]);

  const maxBin = Math.max(1, ...histogram.map((b) => b.count));

  // Per-battery stats
  const batteryStats = useMemo(() => {
    return BATTERIES.map((b) => {
      const json = batteries[b.key];
      const errs = json ? extractErrors(json).map(Math.abs) : [];
      const sorted = [...errs].sort((a, b) => a - b);
      const median = sorted.length > 0 ? sorted[Math.floor(sorted.length / 2)] : null;
      const min = sorted.length > 0 ? sorted[0] : null;
      return { ...b, n: errs.length, median, min };
    });
  }, [batteries]);

  return (
    <>
      <Head>
        <title>Validation | Honjo Masamune</title>
        <meta
          name="description"
          content="One axiom, 142 predictions, 24 orders of magnitude. The Bounded Phase Space framework validated."
        />
      </Head>

      <main className="min-h-screen bg-[#0a0a0a] pt-24 pb-16 px-4">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="mb-10">
            <p className="text-[#58E6D9] text-sm tracking-[0.3em] uppercase mb-2">Framework Validation</p>
            <h1 className="text-4xl md:text-5xl font-bold text-white tracking-tight mb-4">
              One axiom. 142 predictions.
            </h1>
            <p className="text-neutral-400 text-base max-w-3xl">
              Every quantity below — nuclear radii, superconducting transitions, ionisation energies,
              chromatographic retention, electrical resistivity — derives from a single claim: bounded phase spaces
              cannot retain their identity without active renewal. No free parameters. No fits. Click any battery to inspect.
            </p>
          </div>

          {!loaded ? (
            <div className="text-neutral-500 text-sm py-12 text-center">Loading validation data…</div>
          ) : !summary ? (
            <div className="text-neutral-500 text-sm py-12 text-center">
              Validation data not found. Run <code className="text-[#58E6D9]">validate_bounded_phase_space.py</code> and copy
              the JSON outputs into <code className="text-[#58E6D9]">public/validation/</code>.
            </div>
          ) : (
            <>
              {/* Top-level summary */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-10">
                <BigStat label="Axioms" value={summary.axioms} color="#58E6D9" />
                <BigStat label="Predictions" value={summary.summary_stats.n_points} color="#a855f7" />
                <BigStat
                  label="Median |error|"
                  value={`${summary.summary_stats.median_abs_error_pct.toFixed(1)}%`}
                  color="#22c55e"
                />
                <BigStat label="Batteries" value={summary.batteries_run} color="#f97316" />
              </div>

              {/* Error histogram */}
              <section className="bg-neutral-900/40 border border-neutral-800 rounded-2xl p-6 mb-8">
                <h2 className="text-sm font-semibold text-neutral-300 mb-4 uppercase tracking-wider">
                  Error distribution · {allErrors.length} validated predictions
                </h2>
                <div className="grid grid-cols-6 gap-2 items-end h-40 mb-2">
                  {histogram.map((bin) => (
                    <div key={bin.label} className="flex flex-col items-center gap-1 h-full">
                      <div className="text-neutral-500 text-xs font-mono">{bin.count}</div>
                      <div className="w-full flex-1 flex items-end">
                        <div
                          className="w-full rounded-t transition-all duration-700"
                          style={{
                            height: `${(bin.count / maxBin) * 100}%`,
                            backgroundColor:
                              bin.max <= 5 ? "#22c55e" : bin.max <= 15 ? "#58E6D9" : bin.max <= 50 ? "#f97316" : "#ef4444",
                          }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
                <div className="grid grid-cols-6 gap-2">
                  {histogram.map((bin) => (
                    <div key={bin.label} className="text-center text-neutral-500 text-xs">
                      {bin.label}
                    </div>
                  ))}
                </div>
                <p className="text-neutral-600 text-xs mt-4">
                  ~{Math.round((histogram.slice(0, 3).reduce((s, b) => s + b.count, 0) / allErrors.length) * 100)}%
                  of predictions fall within 15% of the measured value. Median absolute error is
                  {" "}
                  <span className="text-white">{summary.summary_stats.median_abs_error_pct.toFixed(1)}%</span> —
                  a zero-parameter deductive framework reproducing a century of experimental data.
                </p>
              </section>

              {/* Per-battery breakdown */}
              <section className="mb-8">
                <h2 className="text-sm font-semibold text-neutral-300 mb-4 uppercase tracking-wider">
                  Batteries
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {batteryStats.map((b) => (
                    <div
                      key={b.key}
                      className="bg-neutral-900/50 border border-neutral-800 rounded-xl p-5"
                    >
                      <div className="flex items-center justify-between mb-2">
                        <h3 className="text-white text-sm font-medium">{b.label}</h3>
                        <div className="w-2 h-2 rounded-full" style={{ backgroundColor: b.color }} />
                      </div>
                      <div className="flex items-baseline gap-2 mb-1">
                        <span className="text-2xl font-bold text-white font-mono">{b.n}</span>
                        <span className="text-neutral-500 text-xs">predictions</span>
                      </div>
                      {b.median !== null && (
                        <>
                          <div className="text-xs text-neutral-400 font-mono">
                            median |err| = <span className="text-white">{b.median.toFixed(2)}%</span>
                          </div>
                          <div className="text-xs text-neutral-500 font-mono">
                            best = {b.min.toFixed(2)}%
                          </div>
                        </>
                      )}
                    </div>
                  ))}
                </div>
              </section>

              {/* Representative anchor predictions */}
              <section className="bg-neutral-900/40 border border-neutral-800 rounded-2xl p-6 mb-8">
                <h2 className="text-sm font-semibold text-neutral-300 mb-4 uppercase tracking-wider">
                  Anchor predictions
                </h2>
                <div className="space-y-2">
                  <Anchor
                    label="Fe-56 binding energy per nucleon"
                    pred={`${summary.Fe56_BE_per_A_predicted_MeV.toFixed(3)} MeV`}
                    meas={`${summary.Fe56_BE_per_A_measured_MeV.toFixed(3)} MeV`}
                    err={Math.abs(summary.Fe56_BE_per_A_predicted_MeV - summary.Fe56_BE_per_A_measured_MeV) /
                      summary.Fe56_BE_per_A_measured_MeV * 100}
                  />
                  <Anchor
                    label="Compton wavelength (electron)"
                    pred={`${summary.compton_wavelength_pm} pm`}
                    meas="2.42631 pm"
                    err={Math.abs(summary.compton_wavelength_pm - 2.42631) / 2.42631 * 100}
                  />
                  <Anchor
                    label="Wiedemann–Franz Lorenz number L₀"
                    pred={`${summary.wiedemann_franz_L_pred.toExponential(4)} W·Ω/K²`}
                    meas="2.44×10⁻⁸ W·Ω/K²"
                    err={Math.abs(summary.wiedemann_franz_L_pred - 2.44e-8) / 2.44e-8 * 100}
                  />
                  <Anchor
                    label="He-4 superfluid λ-transition"
                    pred={`${summary.superfluid_He4.T_lambda_predicted_K} K`}
                    meas={`${summary.superfluid_He4.T_lambda_measured_K} K`}
                    err={summary.superfluid_He4.error_pct}
                  />
                  <Anchor
                    label="Nuclear radii (mean across 20 nuclides)"
                    pred="R = 1.2·A^(1/3) fm"
                    meas="Hofstadter scattering fits"
                    err={summary.nuclear_radii_mean_abs_error_pct}
                  />
                </div>
              </section>

              {/* Parsimony comparison */}
              <section className="bg-gradient-to-br from-neutral-900/60 to-neutral-900/20 border border-neutral-800 rounded-2xl p-6 mb-8">
                <h2 className="text-sm font-semibold text-neutral-300 mb-4 uppercase tracking-wider">
                  Parsimony
                </h2>
                <div className="grid grid-cols-2 gap-6">
                  <div>
                    <div className="text-neutral-500 text-xs uppercase tracking-wider mb-2">Standard Model + GR</div>
                    <div className="text-4xl font-bold text-white font-mono mb-1">~26</div>
                    <div className="text-neutral-500 text-xs">postulates & fitted constants</div>
                    <ul className="text-neutral-600 text-xs mt-3 space-y-0.5">
                      <li>· 3 gauge groups</li>
                      <li>· 12 fermion masses</li>
                      <li>· 4 CKM + 4 PMNS parameters</li>
                      <li>· 3 coupling constants</li>
                    </ul>
                  </div>
                  <div>
                    <div className="text-[#58E6D9] text-xs uppercase tracking-wider mb-2">Bounded Phase Space</div>
                    <div className="text-4xl font-bold text-[#58E6D9] font-mono mb-1">1</div>
                    <div className="text-neutral-500 text-xs">axiom</div>
                    <p className="text-neutral-400 text-xs mt-3 italic">
                      &ldquo;A bounded phase space cannot retain its identity without
                      active renewal against its alternatives.&rdquo;
                    </p>
                  </div>
                </div>
              </section>

              {/* CTA */}
              <div className="flex flex-wrap gap-3 text-sm">
                <Link
                  href="/framework"
                  className="bg-[#58E6D9]/10 text-[#58E6D9] border border-[#58E6D9]/30 rounded-lg px-4 py-2 hover:bg-[#58E6D9]/20 transition"
                >
                  Read the framework →
                </Link>
                <Link
                  href="/tools"
                  className="bg-neutral-800/50 text-white border border-neutral-700 rounded-lg px-4 py-2 hover:bg-neutral-800 transition"
                >
                  Use the instruments →
                </Link>
                <Link
                  href="/resolution"
                  className="bg-neutral-800/50 text-neutral-300 border border-neutral-700 rounded-lg px-4 py-2 hover:bg-neutral-800 transition"
                >
                  The Loschmidt resolution →
                </Link>
              </div>

              <p className="text-neutral-600 text-xs mt-8">
                Validation run: {summary.timestamp_utc}. Framework version {summary.framework_version}.
                All data loaded from static JSON generated by the open-source validation battery.
              </p>
            </>
          )}
        </div>
      </main>
    </>
  );
}

function BigStat({ label, value, color }) {
  return (
    <div className="bg-neutral-900/50 border border-neutral-800 rounded-xl p-5">
      <div className="text-neutral-500 text-xs uppercase tracking-wider mb-2">{label}</div>
      <div className="text-3xl md:text-4xl font-bold font-mono" style={{ color }}>
        {value}
      </div>
    </div>
  );
}

function Anchor({ label, pred, meas, err }) {
  const good = err < 5;
  const ok = err < 20;
  const color = good ? "#22c55e" : ok ? "#58E6D9" : err < 50 ? "#f97316" : "#ef4444";
  return (
    <div className="grid grid-cols-1 md:grid-cols-[2fr_1fr_1fr_0.6fr] gap-3 items-center py-2 border-b border-neutral-800/60 last:border-b-0">
      <div className="text-white text-sm">{label}</div>
      <div className="text-xs">
        <span className="text-neutral-500">predicted </span>
        <span className="font-mono text-[#58E6D9]">{pred}</span>
      </div>
      <div className="text-xs">
        <span className="text-neutral-500">measured </span>
        <span className="font-mono text-neutral-300">{meas}</span>
      </div>
      <div className="text-xs font-mono text-right" style={{ color }}>
        {err.toFixed(2)}%
      </div>
    </div>
  );
}
